version: '3.9'

services:
  account-api:
    build:
      context: ../BankMore/BankMore.AccountService
    ports:
      - "5001:80"
    depends_on:
      - redis
      - kafka
    volumes:
      - ./data/account:/app/data
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - Redis__ConnectionString=redis:6379         
      - Kafka__BootstrapServers=kafka:9092         

  transfer-api:
    build:
      context: ../BankMore/BankMore.TransferService
    ports:
      - "5002:80"
    depends_on:
      - account-api
      - redis
      - kafka
    volumes:
      - ./data/transfer:/app/data
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - Redis__ConnectionString=redis:6379         
      - Kafka__BootstrapServers=kafka:9092         

  tariff-app:
    build:
      context: ../BankMore/BankMore.TariffService
    ports:
      - "5003:80"
    depends_on:
      - kafka
    volumes:
      - ./data/tariff:/app/data
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - Kafka__BootstrapServers=kafka:9092         


  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.1
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.0.1
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:29092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"

volumes:
  redis-data:
